input_file_name: so_dataset_2_tags1.csv
tuning:
  max_evals: 10
  criterion:
    - gini
    - entropy
  max_depth:
    min_range: 1
    max_range: 20
  max_features:
    min_range: 1
    max_range: 5
  n_estimators:
    min_range: 1
    max_range: 20
model_tracking:
  artifact_path: model
  registered_model_name: "ElasticnetWineModel"
